env:
  env_name: SumoIndependentEnv
  agent_nums: 1
  sumo_config_path: 'Env/RL_Arterial_Road_Scenes/standard.sumocfg'
  tls_list: ['1']
  show_gui: True
# 定义日志文件的文件夹
log_dir: "./logs"
policy_name: 'default_policy'
policy_config:
  training_type: 'supervised_learning'
  eval_mode: True
  # ------- 这两个参数在训练RL的时候会使用到，如果都是False，说明actor和critic在一起 --------
  centralized_critic: &centralized_critic False
  seperate_critic: &seperate_critic False
  # ------- 智能体相关的参数 ----------
  parameter_sharing: &parameter_sharing True
  homogeneous_agent: &homogeneous_agent True
  agent:
    policy:
      default:
        learning_rate: 1e-4
        state_dim: 239
        action_dim: 5
        model_name: 'FC_model'
        model_type: 'policy'


  


